// Domain types, derived from the GraphQL operations in lib/api/* (generated by
// codegen from the backend SDL). These are projections of the schema — each
// equals exactly the fields its query selects — so a backend change that drops
// or renames a field surfaces here as a compile error at every use site.

import type {
  BacklinksQuery,
  GetGraphQuery,
  GetNoteQuery,
  GetSidebarDataQuery,
  GetTrashQuery,
  ListFoldersQuery,
  ListNoteStubsQuery,
  ListOrphansQuery,
  SearchQuery,
} from "~/gql/graphql";

export type Note = NonNullable<GetNoteQuery["note"]>;
export type NoteStub = ListNoteStubsQuery["noteStubs"][number];
/** Minimal note reference (e.g. backlinks). */
export type NoteSummary = BacklinksQuery["backlinks"][number];
export type Folder = ListFoldersQuery["folders"][number];
/** Note shape used by the sidebar tree. */
export type SidebarNote = GetSidebarDataQuery["notes"][number];
export type SearchResult = SearchQuery["search"][number];
export type OrphanNote = ListOrphansQuery["orphans"][number];

export type TrashNote = GetTrashQuery["trash"]["notes"][number];
export type TrashFolder = GetTrashQuery["trash"]["folders"][number];

export type GraphData = GetGraphQuery["graphData"];
export type GraphNode = GraphData["nodes"][number];
export type GraphEdge = GraphData["links"][number];
