import { redirect } from "@remix-run/node";
import { print } from "graphql";
import type { TypedDocumentNode } from "@graphql-typed-document-node/core";

const BACKEND_URL = process.env.BACKEND_URL ?? "http://localhost:8000";

// Kept in sync with the backend's get_user_id (app/graphql/types.py).
const UNAUTHENTICATED = "UNAUTHENTICATED";

/**
 * Executes a typed GraphQL document (generated by `graphql()` from ~/gql)
 * against the backend, inferring the result and variables types from it.
 */
export async function request<TResult, TVars>(
  document: TypedDocumentNode<TResult, TVars>,
  variables: TVars,
  token?: string
): Promise<TResult> {
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (token) headers["Authorization"] = `Bearer ${token}`;
  const res = await fetch(`${BACKEND_URL}/graphql`, {
    method: "POST",
    headers,
    body: JSON.stringify({ query: print(document), variables }),
  });

  if (!res.ok) {
    throw new Error(`GraphQL HTTP error: ${res.status}`);
  }

  const json = (await res.json()) as {
    data?: TResult;
    errors?: { message: string }[];
  };

  if (json.errors?.length) {
    const message = json.errors[0].message;
    // Stale/invalid session (e.g. the DB was reset): clear the cookie and send
    // the user to log in again, instead of surfacing an opaque error.
    if (message.includes(UNAUTHENTICATED)) {
      throw redirect("/auth/logout");
    }
    throw new Error(message);
  }

  return json.data as TResult;
}
